[package]
name = "backend"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
async-trait = "=0.1.92"
mads = { version = "=0.8.0", default-features = false, features = ["http", "runtime-tokio"] }
sea-orm = { version = "=1.1.20", features = ["macros", "runtime-tokio-rustls", "sqlx-postgres"] }
serde = { version = "=1.0.229", features = ["derive"] }

[dev-dependencies]
tokio = { version = "=1.53.1", features = ["macros", "rt"] }
