-- Generated by MADS.rs. Review before applying.
-- Unsupported defaults, indexes, checks, triggers, and FK policies are not synthesized.

CREATE TABLE "public"."users" (
    "id" SERIAL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "public"."posts" (
    "id" SERIAL PRIMARY KEY,
    "title" VARCHAR(255) NOT NULL,
    "body" TEXT NOT NULL,
    "user_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id")
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX "idx_posts_user_id" ON "public"."posts" ("user_id");